from src.models.kpi_models import KPI, KPIThreshold, KPIComparisonMethod

# Default comparison methods for consistency
DEFAULT_MONTHLY_COMPARISON = KPIComparisonMethod(
    type="TREND_MONTHLY",
    description="Compares the current month-to-date value against the full previous month.",
    timeframe_logic="monthly"
)

DEFAULT_YOY_COMPARISON = KPIComparisonMethod(
    type="YOY_QTR",
    description="Compares the current quarter-to-date value against the same quarter in the previous year.",
    timeframe_logic="quarterly_yoy"
)

DEFAULT_BUDGET_COMPARISON = KPIComparisonMethod(
    type="BUDGET_VS_ACTUAL",
    description="Compares actual values against budgeted values for the period.",
    timeframe_logic="current_period"
)

KPI_REGISTRY = [
    KPI(
        name="Gross Revenue",
        description="Total gross revenue recognized in the period.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Gross Revenue'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        filters=[{"column": "account_hierarchy_desc", "value": "Gross Revenue"}],
        dimensions=["region", "profit_center"],
        thresholds=KPIThreshold(warning=0.10, critical=-0.05), # Opportunity: 10% growth, Problem: 5% decline
        positive_trend_is_good=True,
        business_processes=["Finance: Revenue Growth Analysis", "Finance: Profitability Analysis"],
        data_product_id="FI_Star_Schema",
        default_comparison="TREND_MONTHLY",
        comparison_methods=[
            KPIComparisonMethod(
                type="TREND_MONTHLY",
                description="Compares the current month-to-date value against the full previous month.",
                timeframe_logic="monthly"
            ),
            KPIComparisonMethod(
                type="YOY_QTR",
                description="Compares the current quarter-to-date value against the same quarter in the previous year.",
                timeframe_logic="quarterly_yoy"
            )
        ],
    ),
    KPI(
        name="Cost of Goods Sold",
        description="Total cost of goods sold in the period.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Cost of Goods Sold'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        filters=[{"column": "account_hierarchy_desc", "value": "Cost of Goods Sold"}],
        dimensions=["region", "profit_center"],
        thresholds=KPIThreshold(warning=0.05, critical=0.10),
        positive_trend_is_good=False,
        business_processes=["Finance: Profitability Analysis", "Finance: Expense Management"],
        data_product_id="FI_Star_Schema",
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON, DEFAULT_BUDGET_COMPARISON],
    ),
    KPI(
        name="Gross Margin",
        description="Gross Margin is calculated as Gross Revenue minus Cost of Goods Sold.",
        type="financial",
        calculation="Gross Revenue - Cost of Goods Sold",
        aggregation="Derived",
        base_column="value",
        join_tables=["GLAccounts"],
        dependencies=["Gross Revenue", "Cost of Goods Sold"],
        data_product_id="FI_Star_Schema",
        business_processes=["Finance: Profitability Analysis", "Finance: Revenue Growth Analysis"],
        dimensions=["region", "profit_center"],
        thresholds=KPIThreshold(warning=0.10, critical=-0.05), # Opportunity: 10% growth, Problem: 5% decline
        positive_trend_is_good=True,
        default_comparison="TREND_MONTHLY",
        comparison_methods=[
            KPIComparisonMethod(
                type="TREND_MONTHLY",
                description="Compares the current month-to-date value against the full previous month.",
                timeframe_logic="monthly"
            ),
            KPIComparisonMethod(
                type="YOY_QTR",
                description="Compares the current quarter-to-date value against the same quarter in the previous year.",
                timeframe_logic="quarterly_yoy"
            )
        ],
    ),
    KPI(
        name="Running Total Gross Revenue",
        description="Cumulative sum of Gross Revenue by region and profit center.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Gross Revenue'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        window="cumulative",
        partition_by=["region", "profit_center"],
        order_by=["date"],
        dimensions=["region", "profit_center"],
        thresholds=KPIThreshold(warning=0.10, critical=-0.05),
        positive_trend_is_good=True,
        business_processes=["Finance: Revenue Growth Analysis"],
        data_product_id="FI_Star_Schema",
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON],
    ),
    KPI(
        name="Top 3 Profit Centers by Gross Revenue",
        description="Top 3 profit centers by Gross Revenue for the period.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Gross Revenue'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        # Removed incorrect type_kpi parameter
        # Added dependency to base KPI
        dependencies=["Gross Revenue"],
        top_n=3,
        partition_by=["region"],
        order_by=["SUM(value) DESC"],
        dimensions=["region", "profit_center"],
        thresholds=KPIThreshold(warning=0.10, critical=-0.05),
        positive_trend_is_good=True,
        business_processes=["Finance: Revenue Growth Analysis"],
        data_product_id="FI_Star_Schema",
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON],
    ),
    KPI(
        name="Sales Deductions",
        description="Total sales deductions applied in the period.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Sales Deductions'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        filters=[{"column": "account_hierarchy_desc", "value": "Sales Deductions"}],
        thresholds=KPIThreshold(warning=0.05, critical=0.10),
        positive_trend_is_good=False,
        business_processes=["Finance: Revenue Growth Analysis"],
        data_product_id="FI_Star_Schema",
        dimensions=["region", "profit_center"],
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON, DEFAULT_BUDGET_COMPARISON],
    ),
    KPI(
        name="Revenue",
        description="Total revenue generated from sales.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Net Revenue'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        filters=[{"column": "account_hierarchy_desc", "value": "Net Revenue"}],
        dimensions=["region", "profit_center"],
        thresholds=KPIThreshold(critical=-0.10, warning=-0.05),
        positive_trend_is_good=True,
        business_processes=["Finance: Revenue Growth Analysis"],
        data_product_id="FI_Star_Schema",
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON, DEFAULT_BUDGET_COMPARISON],
    ),
    KPI(
        name="Utilities Expense",
        description="Total utilities expense.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Utilities Expense'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        filters=[{"column": "account_hierarchy_desc", "value": "Utilities Expense"}],
        thresholds=KPIThreshold(warning=0.05, critical=0.10),
        positive_trend_is_good=False,
        business_processes=["Finance: Expense Management", "Finance: Budget vs. Actuals"],
        data_product_id="FI_Star_Schema",
        dimensions=["region", "profit_center"],
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON, DEFAULT_BUDGET_COMPARISON],
    ),
    KPI(
        name="Office Expense",
        description="Total office expense.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Office Expense'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        filters=[{"column": "account_hierarchy_desc", "value": "Office Expense"}],
        thresholds=KPIThreshold(warning=0.05, critical=0.10),
        positive_trend_is_good=False,
        business_processes=["Finance: Expense Management", "Finance: Budget vs. Actuals"],
        data_product_id="FI_Star_Schema",
        dimensions=["region", "profit_center"],
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON, DEFAULT_BUDGET_COMPARISON],
    ),
    KPI(
        name="Payroll",
        description="Total payroll expense.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Payroll'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        filters=[{"column": "account_hierarchy_desc", "value": "Payroll"}],
        thresholds=KPIThreshold(warning=0.05, critical=0.10),
        positive_trend_is_good=False,
        business_processes=["Finance: Expense Management", "Finance: Budget vs. Actuals"],
        data_product_id="FI_Star_Schema",
        dimensions=["region", "profit_center"],
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON, DEFAULT_BUDGET_COMPARISON],
    ),
    KPI(
        name="Travel",
        description="Total travel expense.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Travel'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        filters=[{"column": "account_hierarchy_desc", "value": "Travel"}],
        thresholds=KPIThreshold(warning=0.05, critical=0.10),
        positive_trend_is_good=False,
        business_processes=["Finance: Expense Management", "Finance: Budget vs. Actuals"],
        data_product_id="FI_Star_Schema",
        dimensions=["region", "profit_center"],
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON, DEFAULT_BUDGET_COMPARISON],
    ),
    KPI(
        name="Employee Expense Other",
        description="Total employee expense (other).",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Employee Expense Other'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        filters=[{"column": "account_hierarchy_desc", "value": "Employee Expense Other"}],
        thresholds=KPIThreshold(warning=0.05, critical=0.10),
        positive_trend_is_good=False,
        business_processes=["Finance: Expense Management", "Finance: Budget vs. Actuals"],
        data_product_id="FI_Star_Schema",
        dimensions=["region", "profit_center"],
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON, DEFAULT_BUDGET_COMPARISON],
    ),
    KPI(
        name="Other Operating Expense",
        description="Total other operating expense.",
        type="financial",
        calculation="SUM(value) WHERE GLAccounts.account_hierarchy_desc = 'Other Operating Expense'",
        aggregation="SUM",
        base_column="value",
        join_tables=["GLAccounts"],
        filters=[{"column": "account_hierarchy_desc", "value": "Other Operating Expense"}],
        thresholds=KPIThreshold(warning=0.05, critical=0.10),
        positive_trend_is_good=False,
        business_processes=["Finance: Expense Management", "Finance: Budget vs. Actuals"],
        data_product_id="FI_Star_Schema",
        dimensions=["region", "profit_center"],
        default_comparison="TREND_MONTHLY",
        comparison_methods=[DEFAULT_MONTHLY_COMPARISON, DEFAULT_BUDGET_COMPARISON],
    )
]