metadata:
  id: dp_lubricants_financials
  name: Lubricants Business Financial Analytics
  description: >
    Lubricants industry financial star schema with revenue, profitability,
    and operational KPIs across product lines, customer segments, channels,
    and business divisions. Source: BigQuery agent9-465818.LubricantsBusiness.
  domain: Finance
  owner: Finance Analytics Team
  version: "1.0.0"
  source_system: bigquery
  tags:
    - finance
    - lubricants
    - bigquery
    - demo
    - oil-and-gas

supported_business_processes:
  - "Finance: Profitability Analysis"
  - "Finance: Revenue Growth Analysis"
  - "Finance: Expense Management"

# Canonical column aliases for SQL generation
column_aliases:
  measure: "amount"
  date: "transaction_date"
  version: "version"
  default_version_value: "Actual"

# Business term mapping for LLM and UI
business_terms:
  product_line:
    column: product_line
    description: "Product line (Engine Oils, Industrial Lubricants, etc.)"
  customer_segment:
    column: customer_segment
    description: "Customer segment (Retail Partners, Service Centers, Commercial Fleet, etc.)"
  channel:
    column: channel_name
    description: "Sales channel (DIY Retail, DIFM Service Centers, B2B Direct, E-Commerce, International)"
  profit_center:
    column: profit_center_name
    description: "Profit center / business division"
  account_type:
    column: account_type
    description: "Account type (Revenue, COGS, SGA, Other)"
  account_category:
    column: account_category
    description: "Account category (Product Sales, Raw Materials, Distribution, etc.)"

fallback_group_by_dimensions:
  - product_line
  - channel
  - profit_center

views:
  - name: LubricantsStarSchemaView
    llm_profile:
      exposed_columns:
        - "transaction_id"
        - "fiscal_year"
        - "fiscal_period"
        - "transaction_date"
        - "amount"
        - "version"
        - "currency"
        - "account_name"
        - "account_type"
        - "account_category"
        - "account_group"
        - "product_name"
        - "product_line"
        - "product_category"
        - "customer_name"
        - "customer_segment"
        - "customer_region"
        - "profit_center_name"
        - "business_unit"
        - "channel_name"
        - "channel_type"
      dimension_semantics:
        # Product dimensions
        - "product_name"
        - "product_line"
        - "product_category"
        # Customer dimensions
        - "customer_name"
        - "customer_segment"
        - "customer_region"
        # Organization dimensions
        - "profit_center_name"
        - "business_unit"
        # Channel dimensions
        - "channel_name"
        - "channel_type"
        # Account dimensions
        - "account_name"
        - "account_type"
        - "account_category"
        - "account_group"
        # Time dimensions
        - "fiscal_year"
        - "fiscal_period"
        - "transaction_date"
    sql: |
      SELECT
        transaction_id,
        fiscal_year,
        fiscal_period,
        transaction_date,
        amount,
        version,
        currency,
        account_name,
        account_type,
        account_category,
        account_group,
        product_name,
        product_line,
        product_category,
        customer_name,
        customer_segment,
        customer_region,
        profit_center_name,
        business_unit,
        channel_name,
        channel_type
      FROM `agent9-465818.LubricantsBusiness.LubricantsStarSchemaView`

# Connection metadata for BigQuery
connection:
  type: bigquery
  project: agent9-465818
  dataset: LubricantsBusiness
  view: LubricantsStarSchemaView

kpis:
  - name: Net Revenue
    description: "Total net revenue across all channels and product lines"
    data_product_id: dp_lubricants_financials
    aggregation: SUM
    base_column: amount
    filter_type: account_type
    filter_value: Revenue
    unit: "$"
    join_tables:
      - LubricantsStarSchemaView
    business_terms:
      - "Finance: Revenue Growth Analysis"
      - "Finance: Profitability Analysis"
    thresholds:
      warning:
        value: -2.0
        description: "Revenue declining vs comparison period"
      critical:
        value: -5.0
        description: "Significant revenue drop"
    diagnostic_questions:
      - "Which channel is driving the revenue change?"
      - "Which product line shows the most variance?"
      - "Is the change concentrated in specific customer segments?"

  - name: Service Revenue
    description: "Revenue from service centers (quick lube, dealer service)"
    data_product_id: dp_lubricants_financials
    aggregation: SUM
    base_column: amount
    filter_type: account_category
    filter_value: Service Revenue
    unit: "$"
    join_tables:
      - LubricantsStarSchemaView
    business_terms:
      - "Finance: Revenue Growth Analysis"
    thresholds:
      warning:
        value: -5.0
        description: "Service revenue declining"
      critical:
        value: -8.0
        description: "Significant service revenue drop"

  - name: Gross Margin %
    description: "Gross Profit as percentage of Revenue (target: 33-37%)"
    data_product_id: dp_lubricants_financials
    calculation: "(SUM(CASE WHEN account_type IN ('Revenue','COGS') THEN amount ELSE 0 END) / NULLIF(SUM(CASE WHEN account_type = 'Revenue' THEN amount ELSE 0 END), 0)) * 100"
    unit: "%"
    join_tables:
      - LubricantsStarSchemaView
    business_terms:
      - "Finance: Profitability Analysis"
    thresholds:
      warning:
        value: 30.0
        description: "Gross margin below target range"
      critical:
        value: 28.0
        description: "Gross margin critically low"

  - name: Cost of Goods Sold
    description: "Total COGS including base oil, blending, packaging, and distribution"
    data_product_id: dp_lubricants_financials
    aggregation: SUM
    base_column: amount
    filter_type: account_type
    filter_value: COGS
    calculation: "SUM(-amount) WHERE account_type = 'COGS'"
    unit: "$"
    join_tables:
      - LubricantsStarSchemaView
    business_terms:
      - "Finance: Expense Management"
      - "Finance: Profitability Analysis"
    thresholds:
      warning:
        value: 5.0
        description: "COGS increasing faster than expected"
      critical:
        value: 10.0
        description: "COGS spike - investigate raw material costs"
    diagnostic_questions:
      - "Which COGS component (base oil, blending, packaging, distribution) is driving the increase?"
      - "Is the cost increase across all profit centers or concentrated?"
      - "How does the cost trend compare to commodity price indices?"

  - name: Base Oil & Additives Cost
    description: "Raw material costs for base oil and additives (volatile, key risk factor)"
    data_product_id: dp_lubricants_financials
    aggregation: SUM
    base_column: amount
    filter_type: account_category
    filter_value: Raw Materials
    calculation: "SUM(-amount) WHERE account_category = 'Raw Materials'"
    unit: "$"
    join_tables:
      - LubricantsStarSchemaView
    business_terms:
      - "Finance: Expense Management"
    thresholds:
      warning:
        value: 5.0
        description: "Base oil costs rising"
      critical:
        value: 15.0
        description: "Base oil cost spike - crude oil volatility"

  - name: SG&A Expense
    description: "Selling, General & Administrative expenses"
    data_product_id: dp_lubricants_financials
    aggregation: SUM
    base_column: amount
    filter_type: account_type
    filter_value: SGA
    calculation: "SUM(-amount) WHERE account_type = 'SGA'"
    unit: "$"
    join_tables:
      - LubricantsStarSchemaView
    business_terms:
      - "Finance: Expense Management"
    thresholds:
      warning:
        value: 5.0
        description: "SG&A over budget"
      critical:
        value: 10.0
        description: "SG&A significantly over budget"

  - name: E-Commerce Revenue
    description: "Revenue from e-commerce / digital channel"
    data_product_id: dp_lubricants_financials
    aggregation: SUM
    base_column: amount
    filters:
      channel_name: "E-Commerce"
      account_type: "Revenue"
    unit: "$"
    join_tables:
      - LubricantsStarSchemaView
    business_terms:
      - "Finance: Revenue Growth Analysis"
    thresholds:
      warning:
        value: 5.0
        description: "E-Commerce growth slowing"
      critical:
        value: -5.0
        description: "E-Commerce revenue declining"

  - name: B2B Direct Revenue
    description: "Revenue from B2B direct sales channel (fleet + industrial)"
    data_product_id: dp_lubricants_financials
    aggregation: SUM
    base_column: amount
    filters:
      channel_name: "B2B Direct Sales"
      account_type: "Revenue"
    unit: "$"
    join_tables:
      - LubricantsStarSchemaView
    business_terms:
      - "Finance: Revenue Growth Analysis"
    thresholds:
      warning:
        value: -2.0
        description: "B2B revenue declining"
      critical:
        value: -8.0
        description: "Significant B2B revenue loss - check fleet customers"
    diagnostic_questions:
      - "Which fleet customer is driving the decline?"
      - "Is it a single customer loss or broad-based?"
      - "Has a competitor won key accounts?"
