metadata:
  id: dp_test_agent
  name: Dp Test Agent
  domain: Unknown
tables:
- name: financial_transactions
  columns: []
views:
- name: dp_test_agent_financial_transactions_view
  sql: SELECT  FROM financial_transactions
  source_table: financial_transactions
kpis: []
