"""
Deterministic groundedness scoring for SF options.

WHY THIS EXISTS
---------------
Every quality signal SF currently produces is generated by the same LLM call that
wrote the option — including the moderator's own `arithmetic_consistency` grade.
That grade checks an option against *its own claimed inputs*, never against the
data. Observed live (2026-08-06): it returned `pass` on this option

    "Structural Margin Governance & Best-Practice Replication Program"
    impact: 26-47 percentage points, scope=enterprise

on a KPI whose actual enterprise move was **-1.67pp**. The claim was built by
summing unweighted segment-level pp deltas (43.24 + 16.76 + 15.18 = 75.18) across
segments with different revenue weights — a methodology the grader never examined
because it only verified internal consistency with the option's own arithmetic.

These six checks are computed from data alone. No LLM, no model judgement.

NOT-CHECKED IS NOT PASS
-----------------------
Every check returns `True` / `False` / `None`, where `None` means "the input
needed to check this was not supplied" (e.g. running offline against a saved
payload with no registry connection). `None` is excluded from both numerator and
denominator of the score. Conflating "not checked" with "passed" is precisely the
failure mode this module exists to catch, so it is not repeated here.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Set

# A recovery range may legitimately reach the size of the observed decline
# (recover everything that was lost). Claiming materially MORE than that means
# "we will end up better than we started", which is a different and stronger
# claim than recovery. 1.2 allows 20% headroom for rounding and for genuinely
# ambitious-but-arguable estimates; beyond it, the number wants justification.
PLAUSIBILITY_CEILING = 1.2


@dataclass
class DAFacts:
    """The observed magnitudes an impact claim has to answer to."""
    kpi_name: Optional[str] = None
    enterprise_delta: Optional[float] = None          # absolute pp/unit move of the headline KPI
    segment_deltas: Dict[str, float] = field(default_factory=dict)  # normalized key -> abs delta

    def segment_delta_for(self, label: Optional[str]) -> Optional[float]:
        """Resolve a scope_label to its observed delta, tolerating partial names.

        SF writes labels like "National Auto Parts Chain A & Synthetic Blend Engine
        Oil" (a compound scope) or just "Chain A". Exact match first, then
        containment either way, then the largest delta among all segments the
        label mentions — a compound scope is bounded by the sum of the segments it
        names, but we use max() rather than sum() deliberately: summing segment pp
        deltas is the very error this module exists to flag.
        """
        if not label:
            return None
        key = _norm(label)
        if key in self.segment_deltas:
            return self.segment_deltas[key]
        hits = [d for seg, d in self.segment_deltas.items() if seg in key or key in seg]
        return max(hits) if hits else None

    def segment_delta_sum(self) -> float:
        return sum(self.segment_deltas.values())


@dataclass
class GroundednessScore:
    option_id: str
    g1_scope_stated: Optional[bool] = None
    g2_scope_consistent: Optional[bool] = None
    g3_arithmetic_plausible: Optional[bool] = None
    g4_causal_edge_known: Optional[bool] = None
    g5_constraints_addressed: Optional[bool] = None
    g6_not_stub: Optional[bool] = None
    # Magnitude, not just verdict: "claimed 28.1x the observed move" is the
    # actionable fact; a bare False loses it.
    impact_ratio: Optional[float] = None
    cross_segment_summation: bool = False
    reasons: List[str] = field(default_factory=list)

    def _checks(self) -> List[Optional[bool]]:
        return [self.g1_scope_stated, self.g2_scope_consistent, self.g3_arithmetic_plausible,
                self.g4_causal_edge_known, self.g5_constraints_addressed, self.g6_not_stub]

    @property
    def checked(self) -> int:
        return sum(1 for c in self._checks() if c is not None)

    @property
    def passed(self) -> int:
        return sum(1 for c in self._checks() if c is True)

    @property
    def score(self) -> Optional[float]:
        return (self.passed / self.checked) if self.checked else None


def _norm(text: Optional[str]) -> str:
    return re.sub(r"\s+", " ", (text or "")).strip().lower()


# "Gross Margin % is 32.55 vs last_year 34.22 (Δ -1.67, -4.9%)."
_HEADLINE_DELTA = re.compile(r"[\(\[]\s*[Δ∆d]\s*(-?\d+(?:\.\d+)?)", re.IGNORECASE)


def extract_da_facts(da_result: Dict[str, Any]) -> DAFacts:
    """Pull the observed magnitudes out of a Deep Analysis result.

    Enterprise delta comes from the `what_is` narrative line, which is the only
    place DA states the headline move. If that line changes shape the regex
    returns None and G3 degrades to not-checked — deliberately, rather than
    silently scoring against a wrong or absent baseline.
    """
    execution = da_result.get("execution") or da_result
    facts = DAFacts(kpi_name=(da_result.get("plan") or {}).get("kpi_name"))

    kt = execution.get("kt_is_is_not") or {}
    for item in kt.get("what_is") or []:
        text = item.get("text") if isinstance(item, dict) else str(item)
        m = _HEADLINE_DELTA.search(text or "")
        if m:
            facts.enterprise_delta = abs(float(m.group(1)))
            break

    for cp in execution.get("change_points") or []:
        if not isinstance(cp, dict):
            continue
        key, delta = cp.get("key"), cp.get("delta")
        if key and isinstance(delta, (int, float)):
            facts.segment_deltas[_norm(key)] = abs(float(delta))

    return facts


def score_option(
    option: Dict[str, Any],
    da_facts: DAFacts,
    *,
    moderator_grade: Optional[Dict[str, Any]] = None,
    known_causal_edges: Optional[Set[str]] = None,
    active_constraints: Optional[Iterable[str]] = None,
    is_stub_run: Optional[bool] = None,
) -> GroundednessScore:
    """Score one option. Optional inputs left as None yield not-checked results."""
    from src.analysis.mechanism import normalize_causal_edge  # local: avoid import cycle

    oid = str(option.get("id") or "?")
    s = GroundednessScore(option_id=oid)
    ie = option.get("impact_estimate") or {}
    scope = ie.get("scope")
    scope_label = ie.get("scope_label")
    rr = ie.get("recovery_range") or {}
    high = rr.get("high")

    # ---- G6: is this the heuristic stub? -----------------------------------
    if is_stub_run is not None:
        s.g6_not_stub = not is_stub_run
        if is_stub_run:
            s.reasons.append("run fell back to the hardcoded heuristic stub")

    # ---- G1: scope stated at all -------------------------------------------
    s.g1_scope_stated = scope in ("enterprise", "segment")
    if not s.g1_scope_stated:
        s.reasons.append("impact scope unstated — must be read as unverified, never assumed enterprise")

    # ---- G2: scope internally consistent -----------------------------------
    # An 'enterprise' claim that names a specific segment contradicts itself. The
    # SF parser already resets this to None at ingest (PM-7), so a payload read
    # post-parse shows scope=None; the contradiction is caught by G1 there. This
    # check catches the raw case (pre-parse or externally supplied).
    if scope is not None:
        s.g2_scope_consistent = not (scope == "enterprise" and bool(scope_label))
        if not s.g2_scope_consistent:
            s.reasons.append(f"claims enterprise scope while naming segment {scope_label!r}")

    # ---- G3: arithmetic plausible against OBSERVED magnitudes --------------
    if isinstance(high, (int, float)):
        ceiling = None
        basis_desc = ""
        if scope == "segment":
            ceiling = da_facts.segment_delta_for(scope_label)
            basis_desc = f"segment {scope_label!r} observed move"
        elif scope == "enterprise":
            ceiling = da_facts.enterprise_delta
            basis_desc = "enterprise observed move"

        if ceiling:
            ratio = abs(float(high)) / ceiling
            s.impact_ratio = round(ratio, 2)
            s.g3_arithmetic_plausible = ratio <= PLAUSIBILITY_CEILING
            if not s.g3_arithmetic_plausible:
                s.reasons.append(
                    f"claims {high} vs {basis_desc} of {ceiling:g} ({ratio:.1f}x)"
                )
                # The specific methodological error worth naming: an enterprise
                # claim that is implausible against the enterprise move but sits
                # within the SUM of segment moves is almost certainly built by
                # adding unweighted segment pp deltas together.
                if scope == "enterprise":
                    seg_sum = da_facts.segment_delta_sum()
                    if seg_sum and abs(float(high)) <= seg_sum * PLAUSIBILITY_CEILING:
                        s.cross_segment_summation = True
                        s.reasons.append(
                            f"consistent with summing unweighted segment deltas "
                            f"(sum={seg_sum:g}) — segments carry different weights, "
                            f"so they do not compose linearly into an enterprise figure"
                        )

    # ---- G4: cited causal edge is a real registered edge --------------------
    if known_causal_edges is not None and moderator_grade is not None:
        edge = normalize_causal_edge(moderator_grade.get("causal_grounding"))
        if edge in (None, "ungrounded", "insufficient_data"):
            s.g4_causal_edge_known = False
            s.reasons.append(f"no verified causal edge cited (got {edge or 'nothing'})")
        else:
            s.g4_causal_edge_known = edge in known_causal_edges
            if not s.g4_causal_edge_known:
                s.reasons.append(f"cites causal edge {edge!r} absent from the registry")

    # ---- G5: active constraints addressed ----------------------------------
    # WEAKER THAN G1-G4 BY DESIGN. Whether an option "violates" a constraint is a
    # semantic judgement no regex can make honestly. What IS deterministic:
    # whether the option's own text engages with the constraint at all. An option
    # that proposes repricing and never mentions an active price-lock is not
    # visibly respecting it. Read as "addressed", never as "complied".
    if active_constraints is not None:
        constraints = [c for c in active_constraints if c]
        if constraints:
            blob = _norm(" ".join(str(option.get(k) or "") for k in
                                  ("title", "description", "rationale")) +
                         " " + " ".join(str(p) for p in (option.get("prerequisites") or [])))
            unaddressed = [c for c in constraints if not _constraint_referenced(c, blob)]
            s.g5_constraints_addressed = not unaddressed
            for c in unaddressed:
                s.reasons.append(f"does not visibly address active constraint: {str(c)[:80]!r}")

    return s


# Content words only — matching on "cannot"/"the"/"on" would make every option
# look compliant. 4+ chars drops most function words without a stopword list.
_CONTENT_WORD = re.compile(r"[a-z]{4,}")
_GENERIC = {"cannot", "must", "should", "will", "have", "this", "that", "with", "from",
            "they", "them", "their", "there", "than", "then", "been", "being", "make"}


def _constraint_referenced(constraint: str, option_blob: str) -> bool:
    """True when the option's text engages with a constraint's distinctive terms.

    Requires >=50% of the constraint's content words to appear. A single shared
    word ("pricing") is not engagement — nearly every option in a margin scenario
    mentions pricing.
    """
    words = {w for w in _CONTENT_WORD.findall(_norm(constraint)) if w not in _GENERIC}
    if not words:
        return True  # nothing distinctive to look for; do not penalise the option
    hits = sum(1 for w in words if w in option_blob)
    return hits / len(words) >= 0.5
